[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"  # Your contract's Solidity version
optimizer = true

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"  # Default local Anvil RPC endpoint
